const items = [
  {
    name: "Grilltopia",
    rating: "4.5",
    cost: 2,
    location: "Downtown LA",
    image: "/Work_pics/cci_work.jpg",
    promotion: true,
  },
  {
    name: "Noodle Nest",
    rating: "4.2",
    cost: 1,
    location: "Brooklyn",
    image: "/Work_pics/cci_work.jpg",
    promotion: false,
  },
  {
    name: "Taco Town",
    rating: "4.7",
    cost: 2,
    location: "Houston",
    image: "/Work_pics/cci_work.jpg",
    promotion: true,
  },
  {
    name: "Pizza Planet",
    rating: "4.0",
    cost: 3,
    location: "Orlando",
    image: "/Work_pics/cci_work.jpg",
    promotion: false,
  },
  {
    name: "Spice Street",
    rating: "5",
    cost: 4,
    location: "Chicago",
    image: "/Work_pics/cci_work.jpg",
    promotion: true,
  },
  {
    name: "Veggie Vibe",
    rating: "4.3",
    cost: 2,
    location: "San Diego",
    image: "/Work_pics/cci_work.jpg",
    promotion: false,
  },
  {
    name: "Sushi Storm",
    rating: "4.8",
    cost: 3,
    location: "Seattle",
    image: "/Work_pics/cci_work.jpg",
    promotion: true,
  },
  {
    name: "Burgerville",
    rating: "4.1",
    cost: 1,
    location: "Austin",
    image: "/Work_pics/cci_work.jpg",
    promotion: false,
  },
  {
    name: "Pasta Palace",
    rating: "4.9",
    cost: 3,
    location: "San Francisco",
    image: "/Work_pics/cci_work.jpg",
    promotion: true,
  },
  {
    name: "Curry Kingdom",
    rating: "4.4",
    cost: 2,
    location: "New Jersey",
    image: "/Work_pics/cci_work.jpg",
    promotion: false,
  },
  {
    name: "Pho Paradise",
    rating: "4.6",
    cost: 2,
    location: "Atlanta",
    image: "/Work_pics/cci_work.jpg",
    promotion: true,
  },
  {
    name: "Bento Box",
    rating: "4.2",
    cost: 1,
    location: "Boston",
    image: "/Work_pics/cci_work.jpg",
    promotion: false,
  },
  {
    name: "Flame & Fork",
    rating: "5",
    cost: 5,
    location: "Las Vegas",
    image: "/Work_pics/cci_work.jpg",
    promotion: true,
  },
  {
    name: "The Vegan Fork",
    rating: "4.3",
    cost: 3,
    location: "Portland",
    image: "/Work_pics/cci_work.jpg",
    promotion: false,
  },
  {
    name: "BBQ Haven",
    rating: "4.5",
    cost: 4,
    location: "Nashville",
    image: "/Work_pics/cci_work.jpg",
    promotion: true,
  },
  {
    name: "Wok & Roll",
    rating: "4.0",
    cost: 2,
    location: "Philadelphia",
    image: "/Work_pics/cci_work.jpg",
    promotion: false,
  },
  {
    name: "Kebab Kottage",
    rating: "4.7",
    cost: 3,
    location: "Dallas",
    image: "/Work_pics/cci_work.jpg",
    promotion: true,
  },
  {
    name: "Cheesecake Cloud",
    rating: "4.1",
    cost: 2,
    location: "Miami",
    image: "/Work_pics/cci_work.jpg",
    promotion: false,
  },
  {
    name: "Breakfast Blvd",
    rating: "4.4",
    cost: 1,
    location: "Denver",
    image: "/Work_pics/cci_work.jpg",
    promotion: true,
  },
  {
    name: "Burger Binge",
    rating: "4.6",
    cost: 3,
    location: "Phoenix",
    image: "/Work_pics/cci_work.jpg",
    promotion: false,
  },
  // {
  //   name: "Ramen Rush",
  //   rating: "4.8",
  //   cost: 2,
  //   location: "Minneapolis",
  //   image: "/Work_pics/cci_work.jpg",
  //   promotion: true,
  // },
  // {
  //   name: "Crêpe & Coffee",
  //   rating: "4.2",
  //   cost: 2,
  //   location: "Salt Lake City",
  //   image: "/Work_pics/cci_work.jpg",
  //   promotion: false,
  // },
  // {
  //   name: "Seafood Shore",
  //   rating: "4.7",
  //   cost: 4,
  //   location: "New Orleans",
  //   image: "/Work_pics/cci_work.jpg",
  //   promotion: true,
  // },
  // {
  //   name: "Gyoza Garden",
  //   rating: "4.3",
  //   cost: 3,
  //   location: "Sacramento",
  //   image: "/Work_pics/cci_work.jpg",
  //   promotion: false,
  // },
  // {
  //   name: "Donut Drift",
  //   rating: "4.5",
  //   cost: 1,
  //   location: "Detroit",
  //   image: "/Work_pics/cci_work.jpg",
  //   promotion: true,
  // },
  // {
  //   name: "Rice Republic",
  //   rating: "4.0",
  //   cost: 2,
  //   location: "Cincinnati",
  //   image: "/Work_pics/cci_work.jpg",
  //   promotion: false,
  // },
  // {
  //   name: "Steak Station",
  //   rating: "4.9",
  //   cost: 5,
  //   location: "Omaha",
  //   image: "/Work_pics/cci_work.jpg",
  //   promotion: true,
  // },
  // {
  //   name: "Urban Bites",
  //   rating: "4.6",
  //   cost: 3,
  //   location: "Charlotte",
  //   image: "/Work_pics/cci_work.jpg",
  //   promotion: false,
  // },
  // {
  //   name: "Tikka Twist",
  //   rating: "4.4",
  //   cost: 3,
  //   location: "Columbus",
  //   image: "/Work_pics/cci_work.jpg",
  //   promotion: true,
  // },
  // {
  //   name: "Dim Sum Dreams",
  //   rating: "4.2",
  //   cost: 2,
  //   location: "San Jose",
  //   image: "/Work_pics/cci_work.jpg",
  //   promotion: false,
  // },
];

export default items;
